---
deployment:
  tasks:
    - export DEPLOYPATH=/home/joth9587/gadzette.fr/wp-content/themes/gadzette
    - /bin/mkdir -p /home/joth9587/gadzette.fr/wp-content/themes
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -a wp-content/themes/gadzette/. $DEPLOYPATH/
